/**
 * Export utilities for Doctor Frankenstein ideas
 * Supports Markdown, JSON, and PDF export formats
 */

import type { TechItem, FrankensteinAnalysis } from "@/lib/types";
import type { FrankensteinIdeaResult } from "@/features/doctor-frankenstein/api/generateFrankensteinIdea";

export interface ExportData {
  mode: "companies" | "aws";
  tech1: TechItem;
  tech2: TechItem;
  analysis: FrankensteinAnalysis;
  fullAnalysis?: FrankensteinIdeaResult; // Full analysis with all fields
  allTechnologies?: TechItem[]; // All selected technologies
}

/**
 * Generate a Markdown report for a Frankenstein idea
 */
export function generateMarkdownReport(
  data: ExportData,
  locale: string = "en"
): string {
  const { mode, tech1, tech2, analysis } = data;
  const date = new Date().toLocaleDateString(locale);

  return `---
title: ${analysis.ideaName}
mode: ${mode}
tech1: ${tech1.name}
tech2: ${tech2.name}
date: ${new Date().toISOString()}
language: ${locale}
---

# ${analysis.ideaName}

## Technology Fusion

**Technology 1:** ${tech1.name}
- **Category:** ${tech1.category}
- **Description:** ${tech1.description}

**Technology 2:** ${tech2.name}
- **Category:** ${tech2.category}
- **Description:** ${tech2.description}

## Description

${analysis.description}

## Key Features

${analysis.keyFeatures.map((f) => `- ${f}`).join("\n")}

## Target Market

${analysis.targetMarket}

## Unique Value Proposition

${analysis.uniqueValueProposition}

---

*Generated by Doctor Frankenstein on ${date}*
*Mode: ${mode === "companies" ? "Tech Companies" : "AWS Services"}*
`;
}

/**
 * Generate a JSON report for a Frankenstein idea
 */
export function generateJSONReport(data: ExportData): string {
  const { mode, tech1, tech2, analysis } = data;

  const exportData = {
    metadata: {
      generatedAt: new Date().toISOString(),
      mode: mode,
      version: "1.0",
      generator: "Doctor Frankenstein",
    },
    technologies: {
      tech1: tech1,
      tech2: tech2,
    },
    analysis: analysis,
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * Generate and download a PDF report for a Frankenstein idea
 * Uses jsPDF library for PDF generation
 */
export async function generatePDFReport(
  data: ExportData,
  locale: string = "en"
): Promise<void> {
  const { mode, tech1, tech2, analysis, fullAnalysis, allTechnologies } = data;

  // Dynamically import jsPDF to reduce bundle size
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPos = 20;

  // Helper function to add text with automatic page breaks
  const addText = (
    text: string,
    fontSize: number,
    isBold: boolean = false
  ): void => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }

    const lines = doc.splitTextToSize(text, maxWidth);
    const lineHeight = fontSize * 0.5;

    // Check if we need a new page
    if (yPos + lines.length * lineHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPos = margin;
    }

    doc.text(lines, margin, yPos);
    yPos += lines.length * lineHeight + 5;
  };

  // Helper function to add a section heading
  const addHeading = (text: string, level: 1 | 2 = 1): void => {
    yPos += 5; // Add space before heading
    const fontSize = level === 1 ? 16 : 14;
    addText(text, fontSize, true);
  };

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(analysis.ideaName, margin, yPos);
  yPos += 15;

  // Metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const modeText = mode === "companies" ? "Tech Companies" : "AWS Services";
  doc.text(
    `Mode: ${modeText} | Generated: ${new Date().toLocaleDateString(locale)}`,
    margin,
    yPos
  );
  doc.setTextColor(0, 0, 0);
  yPos += 15;

  // Technology Fusion Section
  addHeading("Technology Fusion");
  
  // Use all technologies if available, otherwise just tech1 and tech2
  const techsToShow = allTechnologies && allTechnologies.length > 0 ? allTechnologies : [tech1, tech2];
  
  techsToShow.forEach((tech, index) => {
    addText(`Technology ${index + 1}: ${tech.name}`, 12, true);
    addText(`Category: ${tech.category}`, 10);
    addText(tech.description, 10);
    yPos += 5;
  });

  // If we have full analysis, use all sections
  if (fullAnalysis) {
    // Core Concept
    if (fullAnalysis.core_concept) {
      addHeading("Core Concept");
      addText(fullAnalysis.core_concept, 10);
    }

    // Problem Statement
    if (fullAnalysis.problem_statement) {
      addHeading("Problem Statement");
      addText(fullAnalysis.problem_statement, 10);
    }

    // Proposed Solution
    if (fullAnalysis.proposed_solution) {
      addHeading("Proposed Solution");
      addText(fullAnalysis.proposed_solution, 10);
    }

    // Unique Value Proposition
    if (fullAnalysis.unique_value_proposition) {
      addHeading("Unique Value Proposition");
      addText(fullAnalysis.unique_value_proposition, 10);
    }

    // Target Audience
    if (fullAnalysis.target_audience) {
      addHeading("Target Audience");
      addText(fullAnalysis.target_audience, 10);
    }

    // Business Model
    if (fullAnalysis.business_model) {
      addHeading("Business Model");
      addText(fullAnalysis.business_model, 10);
    }

    // Growth Strategy
    if (fullAnalysis.growth_strategy) {
      addHeading("Growth Strategy");
      addText(fullAnalysis.growth_strategy, 10);
    }

    // Tech Stack
    if (fullAnalysis.tech_stack_suggestion) {
      addHeading("Tech Stack");
      addText(fullAnalysis.tech_stack_suggestion, 10);
    }

    // Risks & Challenges
    if (fullAnalysis.risks_and_challenges) {
      addHeading("Risks & Challenges");
      addText(fullAnalysis.risks_and_challenges, 10);
    }

    // Metrics
    if (fullAnalysis.metrics) {
      addHeading("Metrics");
      addText(`Originality: ${fullAnalysis.metrics.originality_score}/100`, 10);
      addText(`Feasibility: ${fullAnalysis.metrics.feasibility_score}/100`, 10);
      addText(`Impact: ${fullAnalysis.metrics.impact_score}/100`, 10);
      addText(`Scalability: ${fullAnalysis.metrics.scalability_score}/100`, 10);
      addText(`Wow Factor: ${fullAnalysis.metrics.wow_factor}/100`, 10);
    }

    // Summary
    if (fullAnalysis.summary) {
      addHeading("Summary");
      addText(fullAnalysis.summary, 10);
    }
  } else {
    // Fallback to simplified analysis
    // Description Section
    addHeading("Description");
    addText(analysis.description, 10);

    // Key Features Section (if available)
    if (analysis.keyFeatures && analysis.keyFeatures.length > 0) {
      addHeading("Key Features");
      analysis.keyFeatures.forEach((feature) => {
        addText(`• ${feature}`, 10);
      });
    }

    // Target Market Section
    addHeading("Target Market");
    addText(analysis.targetMarket, 10);

    // Unique Value Proposition Section
    addHeading("Unique Value Proposition");
    addText(analysis.uniqueValueProposition, 10);
  }

  // Footer
  yPos = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by Doctor Frankenstein - No Vibe No Code",
    margin,
    yPos
  );

  // Save the PDF with idea name in filename
  // Sanitize the idea name for use in filename
  const sanitizedName = analysis.ideaName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-') // Replace non-alphanumeric with hyphens
    .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
    .substring(0, 50); // Limit length
  
  const filename = `frankenstein-${sanitizedName}-${Date.now()}.pdf`;
  doc.save(filename);
}

/**
 * Trigger download of a text file (Markdown or JSON)
 */
export function downloadTextFile(
  content: string,
  filename: string,
  mimeType: string = "text/plain"
): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
